language: python

cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/download
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install python-tk python3-tk"
install:
  - echo "Other packages should be handled by setuptools"
script:
  - python setup.py test
